<a href="https://colab.research.google.com/github/gabymardones/Competitor-Analysis/blob/main/Ejercicio_GroupBy_GM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df= pd.read_csv('/content/CalIt2 (2).csv', header = None)
df.head()

   0         1         2  3
0  7  07/24/05  00:00:00  0
1  9  07/24/05  00:00:00  0
2  7  07/24/05  00:30:00  1
3  9  07/24/05  00:30:00  0
4  7  07/24/05  01:00:00  0

In [ ]:
df.rename(columns = {0:"flow_ID", 1:"Date", 2:"Time", 3:"Count" }, inplace=True)
df

       flow_ID      Date      Time  Count
0            7  07/24/05  00:00:00      0
1            9  07/24/05  00:00:00      0
2            7  07/24/05  00:30:00      1
3            9  07/24/05  00:30:00      0
4            7  07/24/05  01:00:00      0
...        ...       ...       ...    ...
10075        9  11/05/05  22:30:00      0
10076        7  11/05/05  23:00:00      0
10077        9  11/05/05  23:00:00      0
10078        7  11/05/05  23:30:00      1
10079        9  11/05/05  23:30:00      0

[10080 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10080 entries, 0 to 10079
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   flow_ID  10080 non-null  int64
 1   Date     10080 non-null  object
 2   Time     10080 non-null  object
 3   Count    10080 non-null  int64
dtypes: int64(2), object(2)
memory usage: 315.1+ KB

In [ ]:
filtro = (df["Date"] == "07/24/05") & (df["flow_ID"] == 7)
datos_filtrados = df[filtro]
datos_filtrados

    flow_ID      Date      Time  Count
0         7  07/24/05  00:00:00      0
2         7  07/24/05  00:30:00      1
4         7  07/24/05  01:00:00      0
6         7  07/24/05  01:30:00      0
8         7  07/24/05  02:00:00      0
10        7  07/24/05  02:30:00      2
12        7  07/24/05  03:00:00      0
14        7  07/24/05  03:30:00      0
16        7  07/24/05  04:00:00      0
18        7  07/24/05  04:30:00      0
20        7  07/24/05  05:00:00      0
22        7  07/24/05  05:30:00      0
24        7  07/24/05  06:00:00      0
26        7  07/24/05  06:30:00      0
28        7  07/24/05  07:00:00      0
30        7  07/24/05  07:30:00      2
32        7  07/24/05  08:00:00      0
34        7  07/24/05  08:30:00      0
36        7  07/24/05  09:00:00      0
38        7  07/24/05  09:30:00      1
40        7  07/24/05  10:00:00      0
42        7  07/24/05  10:30:00      0
44        7  07/24/05  11:00:00      1
46        7  07/24/05  11:30:00      0
48        7  07/24/05  12:00:00      0
50        7  07/24/05  12:30:00      0
52        7  07/24/05  13:00:00      0
54        7  07/24/05  13:30:00      0
56        7  07/24/05  14:00:00      0
58        7  07/24/05  14:30:00      0
60        7  07/24/05  15:00:00      0
62        7  07/24/05  15:30:00      0
64        7  07/24/05  16:00:00      0
66        7  07/24/05  16:30:00      0
68        7  07/24/05  17:00:00      1
70        7  07/24/05  17:30:00      2
72        7  07/24/05  18:00:00      4
74        7  07/24/05  18:30:00      1
76        7  07/24/05  19:00:00      2
78        7  07/24/05  19:30:00      1
80        7  07/24/05  20:00:00      0
82        7  07/24/05  20:30:00      0
84        7  07/24/05  21:00:00      3
86        7  07/24/05  21:30:00      2
88        7  07/24/05  22:00:00      0
90        7  07/24/05  22:30:00      0
92        7  07/24/05  23:00:00      2
94        7  07/24/05  23:30:00      0

In [ ]:
datos_filtrados.sort_values(by ="Count", ascending=False)

    flow_ID      Date      Time  Count
72        7  07/24/05  18:00:00      4
84        7  07/24/05  21:00:00      3
76        7  07/24/05  19:00:00      2
92        7  07/24/05  23:00:00      2
30        7  07/24/05  07:30:00      2
10        7  07/24/05  02:30:00      2
86        7  07/24/05  21:30:00      2
70        7  07/24/05  17:30:00      2
68        7  07/24/05  17:00:00      1
74        7  07/24/05  18:30:00      1
38        7  07/24/05  09:30:00      1
78        7  07/24/05  19:30:00      1
44        7  07/24/05  11:00:00      1
2         7  07/24/05  00:30:00      1
64        7  07/24/05  16:00:00      0
62        7  07/24/05  15:30:00      0
58        7  07/24/05  14:30:00      0
60        7  07/24/05  15:00:00      0
0         7  07/24/05  00:00:00      0
66        7  07/24/05  16:30:00      0
54        7  07/24/05  13:30:00      0
80        7  07/24/05  20:00:00      0
82        7  07/24/05  20:30:00      0
88        7  07/24/05  22:00:00      0
90        7  07/24/05  22:30:00      0
56        7  07/24/05  14:00:00      0
48        7  07/24/05  12:00:00      0
52        7  07/24/05  13:00:00      0
22        7  07/24/05  05:30:00      0
4         7  07/24/05  01:00:00      0
6         7  07/24/05  01:30:00      0
8         7  07/24/05  02:00:00      0
12        7  07/24/05  03:00:00      0
14        7  07/24/05  03:30:00      0
16        7  07/24/05  04:00:00      0
18        7  07/24/05  04:30:00      0
20        7  07/24/05  05:00:00      0
24        7  07/24/05  06:00:00      0
50        7  07/24/05  12:30:00      0
26        7  07/24/05  06:30:00      0
28        7  07/24/05  07:00:00      0
32        7  07/24/05  08:00:00      0
34        7  07/24/05  08:30:00      0
36        7  07/24/05  09:00:00      0
40        7  07/24/05  10:00:00      0
42        7  07/24/05  10:30:00      0
46        7  07/24/05  11:30:00      0
94        7  07/24/05  23:30:00      0

In [ ]:
datos_ordenados = datos_filtrados.sort_values("Count", ascending=False)
Top_10 = datos_ordenados.head(10)

In [ ]:
menor =Top_10 ["Count"].min()
#Apply
Top_10["Count"].apply(lambda x:x-menor).mean()

1.1

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%y")

In [ ]:
filtro =(df["Date"].dt.month == 8) & (df["Date"].dt.year == 2005) & (df["flow_ID"] == 7)
datos_agosto = df[filtro]
datos_agosto.groupby(by="Date")["Count"].max()

Date
2005-08-01    18
2005-08-02    16
2005-08-03    26
2005-08-04    40
2005-08-05    17
2005-08-06     8
2005-08-07     3
2005-08-08    16
2005-08-09    19
2005-08-10    25
2005-08-11    16
2005-08-12    21
2005-08-13     5
2005-08-14     3
2005-08-15    17
2005-08-16    24
2005-08-17    22
2005-08-18    39
2005-08-19    23
2005-08-20     3
2005-08-21     4
2005-08-22    23
2005-08-23    25
2005-08-24    17
2005-08-25    24
2005-08-26    22
2005-08-27     3
2005-08-28     7
2005-08-29    15
2005-08-30    47
2005-08-31    19
Name: Count, dtype: int64